apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.appName }}-oidc-secret
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "swim-ed254-provider.labels" . | nindent 4 }}
type: Opaque
stringData:
  OIDC_ENABLED: {{ .Values.oidc.enabled | quote }}
  OIDC_AUTH_SERVER_URL: {{ .Values.oidc.authServerUrl | quote }}
  OIDC_CLIENT_ID: {{ .Values.oidc.clientId | quote }}
  OIDC_CLIENT_SECRET: {{ .Values.oidc.clientSecret | quote }}
