apiVersion: v1
kind: Service
metadata:
  name: swim-ed254-provider
  namespace: swim-demo
  labels:
    app: swim-ed254-provider
    app.kubernetes.io/part-of: swim-ed254
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
  - name: https
    port: 8443
    targetPort: 8443
    protocol: TCP
  selector:
    app: swim-ed254-provider
