apiVersion: v1
kind: Secret
metadata:
  name: swim-ed254-provider-secret
  namespace: swim-demo
  labels:
    app: swim-ed254-provider
    component: credentials
    app.kubernetes.io/part-of: swim-ed254
type: Opaque
stringData:
  POSTGRES_USER: swim-provider
  POSTGRES_PASSWORD: swim-provider

  AMQP_USERNAME: admin
  AMQP_PASSWORD: admin
