apiVersion: v1
kind: Service
metadata:
  name: swim-ed254-provider-internal
  namespace: swim-demo
  labels:
    app: swim-ed254-provider
    app.kubernetes.io/part-of: swim-ed254
spec:
  type: ClusterIP
  ports:
  - name: internal
    port: 9080
    targetPort: 9080
    protocol: TCP
  selector:
    app: swim-ed254-provider
