apiVersion: v1
kind: Secret
metadata:
  name: swim-ed254-provider-oidc-secret
  namespace: swim-demo
  labels:
    app: swim-ed254-provider
    app.kubernetes.io/part-of: swim-ed254
type: Opaque
stringData:
  OIDC_ENABLED: "true"
  OIDC_AUTH_SERVER_URL: "https://rhbk.apps.ocp4.masales.cloud/realms/swim"
  OIDC_CLIENT_ID: "swim-ed254-provider"
  OIDC_CLIENT_SECRET: "CHANGE_ME"
